### ISSUE TITLE
Incompatible changes

### ISSUE THREAD

**Issue by nbruin** [pietvo/fancyhdr#10]
I noticed that with version 4 (and this is documented) there are some incompatible changes. For instance,
```latex
    \usepackage{fancyhdr}
    \pagestyle{style1}
    \AtBeginShipoutNext{\lhead{new header}\lfoot{new footer}} %% EDIT (see below)
```
works differently between version 3 and version 4 (in version 4 the second style change is not propagated because the change is made locally). The old behaviour can be recovered by using `\usepackage[compatV3]{fancyhdr}` instead. There are several problems:
- Archived LaTeX sources will break when typeset on new systems. This will wreak havoc for, for instance ArXiv, who have a vast amount of documents archived in LaTeX. What version of fancyhdr are they going to use? V3? That will be problematic if people expect the new behaviour. V4? That will break their archived materials. As librarians, they will have to opt for V3, since the archived materials cannot be changed. So this incompatible change encourages a schism in the LaTeX ecosystem.
- In this transition phase, code needs to run on both V3 and V4. Does V3 accept the compatV3 option (and not do anything with it)?

The transition phase may be survivable, but the archival one is a real issue. I think an incompatible change like this warrants a new package name, like `fancyhdr2`. The problem is that we cannot go back in time and future-proof historical uses of fancyhdr.

**EDIT** changed the content of the AtBeginShipoutNext because the original example here used `\pagestyle`, which was always local. The code here reflects the original use case how I was confronted with the changed behaviour in fancyhdr.

**Comment by FrankMittelbach** [comment]
@nbruin I agree with you that archival is posing a problem with a living system in which bugs are fixed or features are added (or even incompatible changes are made) but I don't quite agree with your conclusion that the solution should be to keep old versions of the software  in parallel to the current one on each and everybodies local installation for the the purpose of archival in some central place. A better solution is that librarians keep suitable environment snapshots along with the sources they archive and process/reprocess documents according to their source date with the correct software level. That  would be far more economical in resource usage (not millions of parallel versions of packages on each and every deskop out in the field but a single set of snapshots in a few central place).
Note that this is not just an issue for incompatible changes: it is  a problem for any correction as any correction of a bug may alter documents that relied or worked around a bug.

Concerning incompatible changes: rather than starting with fancyhdr3 4 5 6 7  (or caption caption2 caption3 and then back to caption because it didn't work) with the result that many people stay on obsolete versions because they copy their preambles from one document to the next, LaTeX nowadays offers mechanisms to do rollbacks, not just for the kernel software but also for packages (if they choose to implement it, which we recommend for incompatible changes):

 - [A rollback concept for packages and classes](https://www.latex-project.org/publications/2018-FMi-TUB-tb122mitt-version-rollback.pdf)

Applying this, documents will be reprocessable even on much newer LaTeX releases if you just indicate for which release they were originally written. Neither path is perfect, but I strongly believe that to keep LaTeX relevant in the STEM world it is important that people are encouraged to use corrected and improved packages by default  while offering a way for rollback and a sensible archival method, rather than  bloating the distributed software base and have large numbers of documents based on buggy software because people do not know that a corrected version is out there under a new name.

**Comment by pietvo** [comment]
I fully agree with Frank. That would also have been my answer. I think this is what the American Mathematical Society also does. They keep an archive of older LaTeX versions, and record with each paper which LaTeX version was used. If you only update your LaTeX installation once or twice a year for example, without updating individual packages in the meantime, this is quite manageable. And otherwise you would have to record all the versions of the packages used, which is a bit more work. But I think from a management point of view just updating the whole installation at regular points is easier. And I don't think ArXiv can afford to do less.

There are also other situations that requires an archive to keep old versions itself. Some packages make use of internal commands of LaTeX, or even replace these (like the output routine), and some of these may have changed or even disappeared. That means these packages no longer work at modern LaTeX versions. Usually the authors will update the packages to work with the newer LaTeX versions. But sometimes the packages are abandoned or even removed. Papers that make use of these MUST be run with the original LaTeX distribution that was used when they were submitted. Renaming packages doesn't help in this case.

By the way, your example doesn't even work with fancyhdr version 3, because `\pagestyle` is always a local command. So the page style will still be `style1` on the next page. In version 3 commands like `\fancyhead` would be applied globally, but not `\renewcommand{\headrulewidth}`. So you could end up with quite a messy situation, some things being changed locally, and some things globally, and the resulting pagestyle could be an incomprehensible mixture of two (or even more) page styles. That's why I considered it buggy, and decided to change it.

**Comment by nbruin** [comment]
I've updated my original comment to reflect your note. I have adapted the example to more closely resemble the use-case that confronted me with the change in `fancyhdr`. I have since rewritten my class file to avoid the clash.

What you describe indeed sounds like inconsistent/buggy behaviour, so I can see why you changed it. The fact that headers/footers on a page are rather global features makes it feel a little unnatural that they are now (wholly) local: I suspect that is almost always not the desired behaviour, even if it is "correct" in a computer-science type way. If there are ways to let latex make the change in the appropriate enveloping scope instead, I think it would be very helpful to include that in the documentation (which for the most part is already very helpful -- thank you for that). I was really stuck on that until I realized that `\thispagestyle` did just enough for me if I just first (globally) changed the page style to what was needed for the rest of the letter.

I sincerely hope that ArXiv has the resources to properly snapshot LaTeX versions with their manuscripts, because their infrastructure actually depends on being able to properly typeset historical manuscripts from LaTeX.

**Comment by nbruin** [comment]
I think we can close this. It looks like librarians have taken care of archiving properly.

**Comment by pietvo** [comment]
@nbruin I could make a command like ` \globalfancyhdrpagestyle`, so that ` \globalfancyhdrpagestyle{mystyle}` does `\pagestyle{mystyle}` and then change all relevant macros globally. That would include all the 'variables' that are used by fancyhdr, but also the internal LaTeX macros `\@odddhead`, `\@evenhead`, `\@oddfoot` and `\@evenfoot`. It would do this with commands like `\global\let\xxxx\xxxx` for all of them. Then your example could use `\AtBeginShipoutNext{\globalfancyhdrpagestyle{style2}}`.

I have a working prototype of this but I am hesitant. I still have to see a real usage example that can't be solved in another way, e.g. with the use of `\thispagestyle`. If I get a real example, maybe I will add this to the next release.

Anyway, making the changes always global is a bad idea, especially since this would be absolutely wrong for the use in `\thispagestyle`. This is the reason that even in version 3, changes made inside a `\fancypagestyle` are never global, and thus creating the inconsistency.
And this this idea may lead to unexpected consequences if used inappropriately. That is the reason that I choose such a long name for it (to discourage its use).

**Comment by FrankMittelbach** [comment]
Mixing local/global is usually a bad idea, if you do you need to maintain your own stacks which is why nearly everything in LaTeX is just scoped (ie local). We don't yet have full sets of hooks for output routine handling in LaTeX (that will come perhaps this or next year) but one way to achieve something would be like this:
```
\documentclass{article}
\usepackage{lipsum}
\begin{document}

\lipsum
\AddToHookNext{shipout/after}{\AddToHook{cmd/@outputpage/before}[pstyle]{\pagestyle{empty}}}
\hrule  % show where we are
\lipsum
\lipsum

\AddToHookNext{shipout/after}{\RemoveFromHook{cmd/@outputpage/before}[pstyle]}  %% (*)
\hrule  % show where we are
\lipsum
\end{document}
```

The additional `\AddToHookNext` ensure that filling/removing the generic hook `cmd/@outputpage/before` does not happen at a random place in the source but only during the next processing of the OR. Without it the line (*) would be  seen by LaTeX before page 4 is shipped out because the OR is only triggered when LaTeX starts the paragraph following it, i.e. in that case page 4 would also show a page number.

[Mind you, using the generic hook is a sort of a hack here: there should be proper OR hooks but so far there are only those for shipout which is too late because those are executed when the page box has already been built]

For documentation on LaTeX's hook system see `texdoc lthooks-doc`.

**Comment by pietvo** [comment]
@FrankMittelbach Yes, I know it is bad practice. The Textbook warns that it can cause save stack overflow, and anyway, it might be confusing. That's one of the reasons I hesitate to implement this. Another one being that it meddles with `\@oddhead` etc. although in a minor way. I am going to look at your suggestion about the hooks. It also shows a big drawback of changing page style in the middle of the text: it may end up at a different page than you think, because of the asynchrony of the page builder.

I am currently trying to update the fancyhdr documentation about changing page styles, and this is one thing that I am wrestling with. The current documentation still says you can do some changes in `\afterpage`, which isn't true anymore, and `\afterpage is probably the wrong approach anyway, because it skips over float pages. But then maybe your approach also does that, because there is no separate `\@outputpage` call for float pages.

It almost feels like the dilemma's in dealing with the Covid crisis :)

**Comment by nbruin** [comment]
Once I understood the issue, it was possible for me to work around it and not rely on a `\pagestyle` inside the `\AtBeginShipoutNext`. In the relevant classfile for a letterhead, I still need an `\AtBeginDocument` because the first page needs to have contact information typeset that the user specifies after declaring the document class. I also still need an `\AtBeginShipoutNext` because I need to reset `\topmargin, \headheight, \headsep, \textheight`. It just happens that I can avoid pagestyle changes, because I can set them beforehand, globally, using a `\pagestyle{empty}\thispagestyle{firstpage}`. The `firstpage` page style ends up having a a savebox in it that gets populated in the `\AtBeginDocument`, though. It all feels rather hacky, but I don't think this provides a convincing use case for `\globalfancyhdrpagestyle` quite yet.
